### ISSUE TITLE
Error: Invalid environment; fetch is not defined

### ISSUE THREAD

**Issue by Ilia-Khalizev** [caleboleary/SmartGPT#1]
I decided to try SmartGPT, and made everything according to description of this repo. Unfortunately I have troubles with running it.
Here is my bash:  
node -v
v16.15.0

 
 node smartgpt.js "I left 5 clothes out to dry in the sun. It took them 5 hours to dry completely. How long would it take to dry 30 clothes?" --model "gpt-3.5-turbo" --numAsks 4 --logging
Error: Invalid environment; fetch is not defined
    at new ChatGPTAPI (file:../SmartGPT/node_modules/chatgpt/bui
ld/index.js:174:13)
    at main (file:/SmartGPT/smartgpt.js:16:21)
    at file:/SmartGPT/smartgpt.js:82:1
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)
    
    
    
    
 Maybe I need certain node version?

**Comment by caleboleary** [comment]
Yeah, looks like `fetch` was introduced in 17.5. I personally was running v19.8.1 to test this out. 

The chatgpt library I'm using mentions having at least 18 in their install section https://www.npmjs.com/package/chatgpt - and looks like they link to some ways to use earlier versions if upgrading isn't an easy option.

I'll add that to my own readme
